apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-security-report
  
spec:
  selector:
    matchLabels:
      app: github-security-report
  replicas: 1
  template: 
    metadata:
      labels:
        app: github-security-report
    spec:
      containers:
      - name: github-security-report
        image: REPOSITORY_TAG
        resources:
          requests:
            memory: 16Mi
            cpu: 0.05

---
apiVersion: v1
kind: Service
metadata:
  name: github-security-report-svc

spec:
  selector:
    app: github-security-report

  ports:
    - name: http
      port: 80

  type: ClusterIP