name: build_and_deploy

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Log Level'
        required: false
        default: 'warning'
        type: choice
        options:
          - 'debug'
          - 'info'
          - 'warning'
          - 'error'
          - 'critical'
      tags:
        description: 'Tags'
        required: false
        default: 'latest'
        type: choice
        options:
          - 'latest'
          - 'dev'
          - 'qa'
          - 'prod'

permissions:
  id-token: write 
  contents: read  
    
defaults:
  run:
    shell: bash  

env:
  SECRET_KEY: dummy
  IMAGE_NAME: alecbuchanandemo

jobs:

  call-build-and-test:
    uses: ./.github/workflows/build-and-test.yml 

  build-and-push-image:
      runs-on: ubuntu-latest
      needs:
        - call-build-and-test
      steps:
        - uses: actions/checkout@v2

        - name: Setup Build Environment Variables
          run: |-
            echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV
            source $GITHUB_ENV
          shell: bash

        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v2
          with:
            role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
            aws-region: ${{ secrets.AWS_REGION }}

        - name: Login to ECR
          uses: aws-actions/amazon-ecr-login@v1 

        - name: Set Up Docker Buildx
          uses: docker/setup-buildx-action@v2

        - name: Build Docker Image
          uses: docker/build-push-action@v4
          with:
            context: .
            push: false
            tags: ${{ secrets.AWS_ECR_REGISTRY }}:${{ env.VERSION }}
            cache-from: type=gha
            cache-to: type=gha,mode=max
            outputs: type=docker

        - name: Push Docker Image
          run: docker push ${{ secrets.AWS_ECR_REGISTRY }}:${{ env.VERSION }}

  deploy-to-eks:
     # if: github.ref == 'refs/heads/main' #only run on main branch
    runs-on: ubuntu-latest
    environment: prod
    needs:
      - build-and-push-image
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get update && sudo apt-get install gettext-base graphviz
      - name: Setup Build Environment Variables
        run: |-
          echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV
          source $GITHUB_ENV
      - run: |-
          envsubst < gh-deployment.yaml > modified-deployment.yaml
          cat modified-deployment.yaml
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Get KubeConfig
        run: aws eks --region ${{ secrets.AWS_REGION }} update-kubeconfig --name ${{ secrets.AWS_EKS_CLUSTER_NAME }} 
      - name: Deploy to EKS
        run: kubectl apply -f modified-deployment.yaml --namespace=default 
